![imagen](./img/ejercicios.png)

In [7]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [86]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [87]:
print(my_array[::-2])

[9 7 5 3 1]


In [88]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [89]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [90]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [91]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [92]:
print(my_array[2::-1])

[2 1 0]


In [93]:
print(sorted(my_array[:3],reverse=True))

[np.int64(2), np.int64(1), np.int64(0)]


In [94]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [95]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [96]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [97]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [98]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [99]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [100]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [101]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [102]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [103]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [104]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [105]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [106]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [107]:
x == "Loro"

array([ True, False, False,  True, False])

In [108]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [109]:
print(np.where(x== "Loro")[0])

[0 3]


In [110]:
print(np.where(x == "Loro")[0])

[0 3]


In [111]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [112]:
# np.where(x == "Loro", x, np.nan)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [113]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [114]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


In [115]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [ ]:
np.zeros((10)) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
x = np.zeros((10))
print(x.nbytes)

80


In [8]:
x[3] = 1

print(x)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [18]:
y = np.arange(start=10,stop=50)

In [19]:
y[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [25]:
ejercicio_12 = np.array([1,2,0,0,4,0])


def ejercicio_12_funcion (vector):

    new_vector = np.where(vector != 0)
    return new_vector

ejercicio_12_funcion(ejercicio_12)

(array([0, 1, 4]),)

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [30]:
ejercicio_13 = np.random.randint(100, size = (10,10))
ejercicio_13

array([[37, 63, 12, 50, 66, 92,  2, 40, 60, 15],
       [11, 47, 78, 54, 70, 73, 55, 84, 92, 41],
       [11, 56, 18, 63, 65, 66, 51, 66, 84, 47],
       [26, 93, 39, 79, 95, 98,  3, 34, 74,  1],
       [81, 89,  6, 65, 21,  4, 97, 45,  6,  1],
       [20, 56, 66, 52, 64, 28, 12,  3, 30, 73],
       [53, 93, 38, 33, 58,  7, 19, 99, 86, 90],
       [54, 54, 10, 99, 14, 96, 60, 76, 53, 86],
       [73, 55, 90, 67, 44, 44, 68, 56, 56, 18],
       [45, 74, 44, 68,  9, 11, 58, 36, 43, 53]], dtype=int32)

In [31]:
print(ejercicio_13.min())
print(ejercicio_13.max())


1
99


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [32]:
ejercicio_14 = np.random.randint(100, size = (30))
ejercicio_14

array([91, 56, 17, 17, 26, 28, 85, 58,  5, 17, 20,  9, 53, 32, 27, 86, 86,
       59, 89, 46, 66, 62, 70, 32, 85,  6,  8,  5, 15, 97], dtype=int32)

In [35]:
print(np.mean(ejercicio_14))

45.1


## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [34]:
ejercicio_15 = np.random.randint(20, size = (5,5))
ejercicio_15

array([[19, 13, 17,  7, 11],
       [14,  9, 15, 11, 12],
       [ 5, 18,  7, 11, 16],
       [17, 18,  6,  4, 15],
       [ 5, 14,  9, 11, 16]], dtype=int32)

In [38]:
media_ejercicio_15 = np.mean(ejercicio_15)

In [40]:
ejercicio_15_norma = ejercicio_15 - media_ejercicio_15
ejercicio_15_norma

array([[ 7.,  1.,  5., -5., -1.],
       [ 2., -3.,  3., -1.,  0.],
       [-7.,  6., -5., -1.,  4.],
       [ 5.,  6., -6., -8.,  3.],
       [-7.,  2., -3., -1.,  4.]])

In [41]:
np.std(ejercicio_15_norma)

np.float64(4.47213595499958)

## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [42]:
ejercicio_16 = np.arange(start=0,stop=11)
ejercicio_16

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
ejercicio_16_2 = ejercicio_16.copy()

ejercicio_16_2[(ejercicio_16 >= 3) & (ejercicio_16 <= 8)] = -1

ejercicio_16_2

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])